## <u>HAND WRITTEN DIGITS CLASSIFICATION</u>


## Import Library

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Import Data

In [2]:
from sklearn.datasets import load_digits

In [3]:
df = load_digits()

## **Data Preproccessing**

**Flatten Image**

In [4]:
df.images.shape

(1797, 8, 8)

In [5]:
df.images[0]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [6]:
df.images[0].shape

(8, 8)

In [7]:
n_samples = len(df.images)
data = df.images.reshape(n_samples,-1)

In [8]:
data[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [9]:
data[0].shape

(64,)

In [10]:
data.shape

(1797, 64)

## **Scaling the Data**

In [11]:
data.min()

0.0

In [12]:
data.max()

16.0

In [13]:
data=data/16

In [14]:
data.min()

0.0

In [15]:
data.max()

1.0

In [16]:
data[0]

array([0.    , 0.    , 0.3125, 0.8125, 0.5625, 0.0625, 0.    , 0.    ,
       0.    , 0.    , 0.8125, 0.9375, 0.625 , 0.9375, 0.3125, 0.    ,
       0.    , 0.1875, 0.9375, 0.125 , 0.    , 0.6875, 0.5   , 0.    ,
       0.    , 0.25  , 0.75  , 0.    , 0.    , 0.5   , 0.5   , 0.    ,
       0.    , 0.3125, 0.5   , 0.    , 0.    , 0.5625, 0.5   , 0.    ,
       0.    , 0.25  , 0.6875, 0.    , 0.0625, 0.75  , 0.4375, 0.    ,
       0.    , 0.125 , 0.875 , 0.3125, 0.625 , 0.75  , 0.    , 0.    ,
       0.    , 0.    , 0.375 , 0.8125, 0.625 , 0.    , 0.    , 0.    ])

## Train Test Split Data

In [17]:
from sklearn.model_selection import train_test_split 

In [18]:
X_train , X_test, y_train , y_test =train_test_split(data ,df.target , train_size=0.7,random_state=12529)

In [19]:
X_train.shape , X_test.shape, y_train.shape , y_test.shape

((1257, 64), (540, 64), (1257,), (540,))

## **Random  Forest Model**

In [20]:
from sklearn.ensemble import RandomForestClassifier

In [21]:
rf= RandomForestClassifier()

In [22]:
rf.fit(X_train,y_train)

RandomForestClassifier()

## Predict Test Data

In [23]:
y_pred=rf.predict(X_test)

In [24]:
y_pred

array([0, 1, 2, 2, 5, 8, 7, 5, 3, 1, 4, 1, 8, 6, 6, 5, 9, 6, 2, 8, 3, 2,
       5, 1, 8, 3, 1, 7, 8, 9, 0, 7, 6, 1, 3, 1, 5, 3, 9, 8, 1, 8, 6, 5,
       4, 8, 2, 1, 7, 7, 4, 4, 7, 9, 0, 6, 3, 7, 6, 6, 0, 3, 1, 1, 3, 9,
       2, 6, 0, 5, 4, 5, 0, 3, 5, 2, 2, 8, 5, 3, 7, 6, 5, 2, 0, 7, 6, 0,
       7, 6, 0, 4, 4, 6, 8, 7, 0, 2, 8, 0, 6, 1, 5, 4, 2, 2, 4, 2, 3, 4,
       0, 4, 8, 6, 2, 0, 4, 0, 5, 4, 5, 4, 5, 2, 4, 5, 8, 5, 4, 7, 9, 8,
       1, 4, 4, 8, 7, 5, 1, 2, 4, 2, 1, 5, 8, 3, 3, 6, 0, 1, 0, 9, 1, 8,
       9, 2, 0, 8, 3, 7, 3, 5, 4, 2, 9, 2, 7, 1, 0, 6, 4, 1, 9, 8, 6, 8,
       3, 7, 1, 6, 4, 8, 3, 7, 1, 0, 5, 7, 7, 9, 0, 0, 5, 1, 7, 9, 2, 0,
       5, 1, 0, 0, 7, 9, 6, 3, 6, 8, 2, 8, 1, 2, 3, 3, 3, 7, 1, 7, 9, 1,
       3, 0, 4, 5, 6, 7, 9, 1, 2, 0, 5, 3, 3, 0, 0, 0, 3, 7, 6, 4, 8, 4,
       9, 1, 5, 0, 0, 1, 6, 9, 8, 6, 8, 7, 5, 7, 1, 6, 7, 7, 6, 9, 5, 7,
       1, 1, 1, 7, 4, 3, 5, 0, 9, 2, 2, 4, 3, 2, 9, 7, 9, 2, 6, 3, 9, 2,
       0, 5, 7, 8, 2, 6, 7, 7, 0, 1, 1, 4, 2, 9, 0,


## Model Accuracy

In [25]:
from sklearn.metrics import confusion_matrix,classification_report

In [26]:
confusion_matrix(y_test, y_pred)

array([[53,  0,  0,  0,  1,  0,  0,  0,  0,  0],
       [ 0, 59,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  0, 48,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 53,  0,  0,  0,  1,  0,  0],
       [ 0,  0,  0,  0, 48,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0, 51,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 59,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 59,  0,  1],
       [ 0,  0,  1,  0,  0,  1,  0,  0, 52,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0,  1, 48]], dtype=int64)

In [27]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98        54
           1       0.98      1.00      0.99        59
           2       0.98      0.98      0.98        49
           3       1.00      0.98      0.99        54
           4       0.98      0.96      0.97        50
           5       0.98      1.00      0.99        51
           6       1.00      1.00      1.00        59
           7       0.95      0.98      0.97        60
           8       0.98      0.96      0.97        54
           9       0.98      0.96      0.97        50

    accuracy                           0.98       540
   macro avg       0.98      0.98      0.98       540
weighted avg       0.98      0.98      0.98       540

