# <u>WOMEN CLOTHS REVIEW</u>

## Import Dependencies

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Load Data

In [2]:
data = pd.read_csv('Dataset/Womens Clothing E-Commerce Reviews.csv', index_col = 0)

In [3]:
data.rename(columns = {
    'Review Text': 'Review',
    'Recommended IND': 'Recommended',
    'Positive Feedback Count': 'Positive Feedback',
    'Division Name': 'Division',
    'Department Name': 'Department',
    'Class Name': 'Category'},
            inplace = True)

In [149]:
data.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [150]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 2.0+ MB


In [151]:
data.shape

(23486, 10)

## Missing Values

In [152]:
data.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [153]:
data[data['Review'] == ''] = np.NaN

In [154]:
data['Review'].fillna('No Review', inplace = True)

In [155]:
data.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [156]:
data['Review']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

## Define Target(y) and Feature(X)

In [157]:
data.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

In [158]:
X = data['Review']

In [159]:
y = data['Rating']

In [160]:
data['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

## Train Test Split

In [161]:
from sklearn.model_selection import train_test_split

In [162]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, stratify = y, random_state = 12529)

In [163]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

## Feature text coversion to tokens

In [164]:
from sklearn.feature_extraction.text import CountVectorizer

In [165]:
cv = CountVectorizer(
                lowercase = True,
                analyzer = 'word',
                ngram_range = (2, 3),
                stop_words = 'english',
                max_features = 5000
                    )

In [166]:
X_train = cv.fit_transform(X_train)

In [167]:
cv.get_feature_names_out()

array(['0p fit', '10 10', '10 12', ..., 'yellow color', 'yoga pants',
       'zipper little'], dtype=object)

In [168]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [169]:
X_test = cv.fit_transform(X_test)

In [170]:
cv.get_feature_names_out()

array(['10 12', '10 fit', '10 got', ..., 'years old', 'yellow color',
       'yoga pants'], dtype=object)

In [171]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

## Train Model

In [172]:
from sklearn.naive_bayes import MultinomialNB

In [173]:
model = MultinomialNB()

In [174]:
model.fit(X_train, y_train)

MultinomialNB()

## Model Prediction

In [175]:
y_pred = model.predict(X_test)

In [176]:
y_pred.shape

(7046,)

In [177]:
y_pred

array([5., 1., 5., ..., 3., 4., 4.])

## Get Probability of Each Predicted Class

In [178]:
model.predict_proba(X_test)

array([[0.05195875, 0.08260154, 0.17570434, 0.22106802, 0.46866734],
       [0.36050981, 0.05009674, 0.11403525, 0.15638324, 0.31897497],
       [0.03582725, 0.06660584, 0.12226277, 0.21618005, 0.55912409],
       ...,
       [0.05656578, 0.02108659, 0.48254844, 0.02343763, 0.41636156],
       [0.01070241, 0.00656414, 0.00939201, 0.92843325, 0.04490819],
       [0.03736085, 0.04541674, 0.05181356, 0.4371705 , 0.42823834]])

## Model Evaluation

In [3]:
from sklearn.metrics import confusion_matrix, classification_report

In [180]:
print(confusion_matrix(y_test, y_pred))

[[  18   28   29   48  130]
 [  60   40   46  102  222]
 [ 101   86  100  185  389]
 [ 191  161  166  321  684]
 [ 421  401  355  788 1974]]


In [181]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         1.0       0.02      0.07      0.03       253
         2.0       0.06      0.09      0.07       470
         3.0       0.14      0.12      0.13       861
         4.0       0.22      0.21      0.22      1523
         5.0       0.58      0.50      0.54      3939

    accuracy                           0.35      7046
   macro avg       0.21      0.20      0.20      7046
weighted avg       0.39      0.35      0.37      7046



## Recategorize Rating as Poor(0) and Good(1)

In [182]:
data_recategorized = data.replace({'Rating': {1:0, 2:0, 3:0, 4:1, 5:1}})

In [183]:
y = data_recategorized['Rating']

In [184]:
X = data_recategorized['Review']

## Train Test Split

In [185]:
from sklearn.model_selection import train_test_split

In [186]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, stratify = y, random_state = 12529)

In [187]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

## Feature text coversion to tokens

In [188]:
from sklearn.feature_extraction.text import CountVectorizer

In [189]:
cv = CountVectorizer(
                lowercase = True,
                analyzer = 'word',
                ngram_range = (2, 3),
                stop_words = 'english',
                max_features = 5000
                    )

In [190]:
X_train = cv.fit_transform(X_train)

In [191]:
X_test = cv.fit_transform(X_test)

## Re-Train Model

In [192]:
from sklearn.naive_bayes import MultinomialNB

In [193]:
model = MultinomialNB()

In [194]:
model.fit(X_train, y_train)

MultinomialNB()

## Model Prediction

In [195]:
y_pred = model.predict(X_test)

In [196]:
y_pred.shape

(7046,)

In [197]:
y_pred

array([1., 1., 1., ..., 1., 1., 0.])

## Model Evaluation

In [198]:
from sklearn.metrics import confusion_matrix, classification_report

In [199]:
print(confusion_matrix(y_test, y_pred))

[[ 326 1257]
 [1038 4425]]


In [200]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.24      0.21      0.22      1583
         1.0       0.78      0.81      0.79      5463

    accuracy                           0.67      7046
   macro avg       0.51      0.51      0.51      7046
weighted avg       0.66      0.67      0.67      7046

